language: php

php:
  - 7.1

install:
    - composer install

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c phpunit.xml.dist --coverage-clover build/logs/clover.xml

after_success:
  - php vendor/bin/coveralls -v'
